language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - "echo 'user CHIM' > ~/.pause"
    - "git config user.email 'chim@cpan.org'"
    - "git config user.name 'Anton Gerasimov'"
    - "perlbrew --force install-cpanm"
    - "cpanm --version"
    - "cpanm -q -n version"
    - "cpanm -q -n Pod::Readme"
    - "cpanm -q -n Test::CPAN::Meta"
    - "cpanm -q -n Test::Kwalitee"
    - "cpanm -q -n Test::Pod::Coverage"
    - "cpanm -q -n Test::Pod"
    - "cpanm -q -n Test::EOL"
    - "cpanm -q -n Pod::Coverage::TrustPod"
    - "cpanm -n -q Dist::Zilla::Plugin::Test::EOL"
    - "cpanm -n -q Dist::Zilla::Plugin::Test::NoTabs"
    - "cpanm -n -q Dist::Zilla::Plugin::TravisCI::StatusBadge"
    - "cpanm -n -q Dist::Zilla::Plugin::Git"
    - "cpanm -n -q Dist::Zilla::Role::PluginBundle::PluginRemover"
    - "cpanm -n -q Dist::Zilla::Plugin::GithubMeta"

install:
    - "dzil authordeps -I lib | xargs cpanm -q -n && dzil listdeps -I lib | xargs cpanm -q -n"

script:
    - "dzil test --release -I lib"
