language: perl

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    # - "5.8"

before_install:
    - "cpanm -n -q Dist::Zilla::Plugin::Test::EOL"
    - "cpanm -n -q Dist::Zilla::Plugin::Test::NoTabs"

install:
    - "dzil authordeps -I lib | xargs cpanm -q -n && dzil listdeps -I lib | xargs cpanm -q -n"

script:
    - "dzil test --release -I lib"
